'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { AppShell } from '@/components/AppShell'
import { createClient } from '@/lib/supabase/client'

export default function SettingsPage(){
  const supabase=useMemo(()=>createClient(),[])
  const [form,setForm]=useState({business_name:'B&B Suministros',phone:'',address:'',city:'Tres Arroyos / Balneario Reta',default_markup_percent:'20',quote_validity_hours:'48'})
  const [saved,setSaved]=useState(false)
  useEffect(()=>{void (async()=>{const {data}=await supabase.from('settings').select('*').maybeSingle();if(data)setForm({business_name:data.business_name||'B&B Suministros',phone:data.phone||'',address:data.address||'',city:data.city||'',default_markup_percent:String(data.default_markup_percent??20),quote_validity_hours:String(data.quote_validity_hours??48)})})()},[])
  async function save(e:FormEvent){e.preventDefault();setSaved(false);const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from('settings').upsert({user_id:user.id,business_name:form.business_name,phone:form.phone||null,address:form.address||null,city:form.city||null,default_markup_percent:Number(form.default_markup_percent),quote_validity_hours:Number(form.quote_validity_hours)});if(error)return alert(error.message);setSaved(true)}
  return <AppShell><h1 className="text-2xl font-bold">Ajustes</h1><p className="mt-1 text-slate-500">Datos que usará B&B Suministros en presupuestos y reglas de precios.</p><form onSubmit={save} className="mt-6 max-w-2xl rounded-2xl border bg-white p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Nombre comercial<input value={form.business_name} onChange={e=>setForm({...form,business_name:e.target.value})} className="mt-1.5 w-full rounded-xl border px-3 py-2.5 font-normal"/></label><label className="text-sm font-medium">WhatsApp del negocio<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="mt-1.5 w-full rounded-xl border px-3 py-2.5 font-normal"/></label><label className="text-sm font-medium">Dirección<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} className="mt-1.5 w-full rounded-xl border px-3 py-2.5 font-normal"/></label><label className="text-sm font-medium">Localidad / zona<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} className="mt-1.5 w-full rounded-xl border px-3 py-2.5 font-normal"/></label><label className="text-sm font-medium">Margen predeterminado %<input type="number" min="0" step="0.01" value={form.default_markup_percent} onChange={e=>setForm({...form,default_markup_percent:e.target.value})} className="mt-1.5 w-full rounded-xl border px-3 py-2.5 font-normal"/></label><label className="text-sm font-medium">Vigencia presupuesto (horas)<input type="number" min="1" value={form.quote_validity_hours} onChange={e=>setForm({...form,quote_validity_hours:e.target.value})} className="mt-1.5 w-full rounded-xl border px-3 py-2.5 font-normal"/></label></div><div className="mt-5 flex items-center justify-end gap-3">{saved&&<span className="text-sm text-green-700">Guardado</span>}<button className="rounded-xl bg-brand-600 px-4 py-2 text-sm font-semibold text-white">Guardar ajustes</button></div></form></AppShell>
}
